name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]
assignees:
  -
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the details below to help us reproduce and fix the bug.
  - type: input
    id: bug_description
    attributes:
      label: Bug Description
      description: Describe what went wrong.
      placeholder: "The app crashes when..."
    validations:
      required: true
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: List the steps to reproduce the bug.
      placeholder: |
        1. Open the app
        2. Tap the crash button
    validations:
      required: true
