name: Bug Report
description: Use this template to file a bug report.
title: "[Bug]: "
labels: [ bug, triage ]
assignees:
  -
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the following details to help us reproduce and fix the bug.
  - type: input
    id: bug_description
    attributes:
      label: Description of the Bug
      description: Provide a detailed description of what went wrong.
      placeholder: "Enter a description..."
      value: ""
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: List the steps to reproduce the bug.
      placeholder: "Step 1: …"
      value: ""
projects:
  -
type:
